### ISSUE TITLE
affiliate_tests  are hanging up

### ISSUE THREAD

**Issue by bobinson** [peerplays-network/peerplays#102]
Steps to reproduce:

```
$ tests/chain_test -t affiliate_tests/account_test
```
*Looks like it hangs up on the* tests/tests/affiliate_tests.cpp:198 

```
GRAPHENE_REQUIRE_THROW( db.push_transaction(trx, ~0), fc::assert_exception );
```

**Comment by gladcow** [comment]
Sorry. It was my fail.( This test takes a lot of time (waiting for `HARDFORK_999_TIME` in https://github.com/peerplays-network/peerplays/blob/master/tests/tests/affiliate_tests.cpp#L211), and debugger had pointed me a wrong line when I've checked it first time.(

So, there is no error here really and issue can be closed.

**Comment by bobinson** [comment]
false positive
