### ISSUE TITLE
port cli tests from bitshares to peerplays

### ISSUE THREAD

**Issue by oxarbitrage** [peerplays-network/peerplays#12]
The command line wallet test framework added to bitshares is of great value helping in the creation of new commands and to test existing behaviour. Developers, reviewers and QA will benefit from this addition.

**Comment by xeroc** [comment]
The pull request above refers to an issue not hosted on github, please ignore

**Comment by bobinson** [comment]
We will need to bring this to Peerplays as we will be adding additonal features and commands to the cli_wallet during SONs implementation

**Comment by bobinson** [comment]
fixed with https://github.com/peerplays-network/peerplays/pull/98
