### ISSUE TITLE
forced rebase before merge

### ISSUE THREAD

**Issue by oxarbitrage** [peerplays-network/peerplays#133]
Currently, pull requests to the `develop` branch need to be rebased before being merged. 

A msg will show: 
This branch is out-of-date with the base branch

And no merge will be possible until that is done. This is a bit annoying as each time the develop is updated will force you to do that on each pull even if no related change was done.
It is also noisy as it will be adding this merge commits to the history.

I am not against them but i was wondering if there is any good reason to have it like this. Thanks.

**Comment by RoshanSyed** [comment]
Thanks for the suggestion. It was mostly implemented to resolve some PR conflicts we had. But at this state I agree with you. This has been taken care of, and now it you are not forced to rebase.
