### ISSUE TITLE
BTC-Sidechain tests should be better organized

### ISSUE THREAD

**Issue by bobinson** [peerplays-network/peerplays#15]
It will be great if we can have the BTC-SIDECHAIN implementation code organized into a folder 

https://github.com/peerplays-network/peerplays/tree/feature-sidechain/tests/btc-sidechain

`peerplays/tests/btc-sidechain` - ie

1. Is there anything blocking this ?
2. Any dependencies ?

**Comment by pixelplex** [comment]
@bobinson The unit tests for Bitcoin sidechain have been moved to a separate folder:
https://github.com/peerplays-network/peerplays/tree/feature-sidechain/tests/sidechain_tests

Closing this issue now.

**Comment by bobinson** [comment]
addressed in : https://github.com/peerplays-network/peerplays/commit/329c75668f392e57e588061e18e98762fae82c63
