### ISSUE TITLE
App test doesn't free server port.

### ISSUE THREAD

**Issue by gladcow** [peerplays-network/peerplays#152]
**Bug Description**
Ports 3939 and 4040 a busy after tests/app_test is completed.
 
**Impacts**

- [*] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [*] Deployment (the deployment process after building such as Docker, Gitlab, etc.)
- [*] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [*] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Start `tests\app_test` twice,  one after other. Second run is failed due to busy ports

**Expected Behavior**
Both test starts should be successful

**Host Environment**
 - Host OS:                    Ubuntu 18.04 LTS
 - Host Physical RAM    16GB
 - SSL:                           OpenSSL 1.1.1  11 Sep 2018
 - Boost:                         1.67

**Comment by bobinson** [comment]
fixed by https://github.com/peerplays-network/peerplays/pull/154
