### ISSUE TITLE
ElasticSearch Plugin to support for Peerplays

### ISSUE THREAD

**Issue by bobinson** [peerplays-network/peerplays#161]
ElasticSearch Plugin to support various dApps, API end points, REST APIs, demux etc.

**User Story**

The Elastic Search plugin can help Peerplays to scale easily at the same time providing easy to access, familiar end point to end users.

**Impacts**

- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Gitlab, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
REST API can be made easily available with Elastic Search Plugin

## Community / PBSA check list
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by gladcow** [comment]
ElasticSearch plugin tracks operations and allows witnesses to use less RAM. To track specific objects (proposals, accounts,  Peerplays-specific objects) es-objects plugin is used.

Related Bitshares pull requests to backport:
1. ElasticSearch plugin:
https://github.com/bitshares/bitshares-core/pull/444
https://github.com/bitshares/bitshares-core/pull/873
https://github.com/bitshares/bitshares-core/pull/1201
https://github.com/bitshares/bitshares-core/pull/1458
https://github.com/bitshares/bitshares-core/pull/1693/commits/376f0317d66f70e0daa3a5c9e29d17544bcdb583
https://github.com/bitshares/bitshares-core/pull/1725

2. ES-objects plugin:
https://github.com/bitshares/bitshares-core/pull/500
https://github.com/bitshares/bitshares-core/pull/1271
https://github.com/bitshares/bitshares-core/pull/1429
https://github.com/bitshares/bitshares-core/pull/1541
https://github.com/bitshares/bitshares-core/pull/1717

**Comment by gladcow** [comment]
ElasticSearch 7.5.0 (the latest version at the moment) is working with BitShares plugin,  as far as I can see. Version 7.4 was tested by BitShares: https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin#installation . I think we can use the latest version of the ElasticSearch.

**Comment by gladcow** [comment]
Peerplays-specific objects to add to es-objects plugin indecies: betting markets, bets operations, sports, tournaments, games operations, btc operations.

**Comment by pbattu123** [comment]
Elasticsearch plugin introduced into peerplays and it is available from release @1.4.3
