### ISSUE TITLE
iLog is not receiving 'scheduled_key'

### ISSUE THREAD

**Issue by roelandp** [peerplays-network/peerplays#17]
Something changed with the `capture` object, (used to be just `(capture)`) and now the stdout logs produce lines not displaying the `private_key` as set in config.ini but literally output: 

`1212000ms th_a  witness.cpp:207  block_production_loo ] Not producing block because I don't have the private key for ${scheduled_key}`

Notice ^ _${scheduled_key}_ in above log line ) 

https://github.com/peerplays-network/peerplays/blob/0dc7e8b784b54ef6b75c1d00f9e881673b0edb38/libraries/plugins/witness/witness.cpp#L206

**Comment by bobinson** [comment]
@roelandp  - I assume this is on Alice. Please correct me if I am wrong.

**Comment by satyakoneru** [comment]
https://github.com/peerplays-network/peerplays/pull/63
https://github.com/peerplays-network/peerplays/pull/64

**Comment by bobinson** [comment]
fixed.
