### ISSUE TITLE
Beatrice witness_node hangs, high socket usage, high cpu usage

### ISSUE THREAD

**Issue by space4tech** [peerplays-network/peerplays#198]
**Bug Description**
In a period of time witness_node works good, block propagations works without problem, but in some moment CPU usage start to rise to near 100% and that makes API calls don't answer, can't use cli_wallet and stops to sign/send transactions. You can't know what happens unless you start to measure sockets usage.

I am using prometheus/grafana to track machine logs:
![Grafana](https://i.imgur.com/IcYWunS.png)
3 most relevant quadrants
 - CPU usage metric: node_cpu_seconds_total
 - Socket usage metric: node_sockstat_sockets_used (Number of sockets in state used)
 - Network I/O metric: node_network_receive_bytes_total

witness_node logs: https://file.io/UgCPDi

Start of the problem:
*[16:18] - 1104187ms th_a       websocket_api.cpp:121         on_message           ] API call execution time limit exceeded.*
At 16:18 socket count was 762 and api calls started to be unresponsive.
From there socket count went higher.

At time 21:37 I decided to stop witness_node process, delete database folder and resync from 0. This is showed in the graphs: Socket usage count went down and Network I/O went up because the blockchain download started.

**Impacts**
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Gitlab, etc.)
- [x] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
1. Run *witness_node* on a server and wait until it fully syncs
2. Process will run smoothly until socket count start to rise
3. When CPU usage is high (near 100%) try to make an API call, or use cli_wallet

**Expected Behavior**
Process should run smoothly all the time like previous versions

**Host Environment**
 - Host OS: Ubuntu 16.04.6 LTS
 - Host Physical RAM: 8GB
 - Peerplays Version: test-1.4.0
 - OpenSSL Version: OpenSSL 1.0.2g  1 Mar 2016
 - Boost Version: 1.67
 - 2vCPU (Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz) 
 - 40GB SSD

## PBSA / Developer tasks

- [x] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by bobinson** [comment]
Thank you @space4tech. We are working on this.

**Comment by bobinson** [comment]
The fix under testing can be accessed as follows:

```
git clone https://github.com/peerplays-network/peerplays.git
cd peerplays
git checkout remotes/origin/GRPH134_#198-HighCPU_Usage
git submodule update --init --recursive
cd libraries/fc/
git checkout 961452f06ffc5740c9b95819dde8f6f7babcd2b0
cd -
cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=Release
make -j$(nproc)
```

**Comment by bobinson** [comment]
Fix:

https://github.com/peerplays-network/peerplays-fc/pull/7 
https://github.com/peerplays-network/peerplays/pull/213

This is under QA.

**Comment by bobinson** [comment]
This is fixed.
