### ISSUE TITLE
PPY node crashing on processing bitcoin issue proposal in testnet mode

### ISSUE THREAD

**Issue by pbattu123** [peerplays-network/peerplays#25]
Peerplays node is entering into infinite loop on processing bitcoin issue proposal from in **testnet mode(not in -regtest mode)**

Start the sidechain PPY node and make sure it's generating blocks.
Bring up the bitcoin node in -testnet mode and maintain balance from available faucets. Then transfer some BTC to generated address of PPY node. 
Since it takes 6 confirmations, wait until 6th confirmation of BTC node and look at the logs.
It crashes on processing sidechain proposals(no proposal id found)

Below is the log output for reference

873000ms th_a       witness.cpp:227               block_production_loo ] Not producing block because node didn't wake up within 500ms of the slot time.
2874000ms th_a       witness.cpp:284               maybe_produce_block  ] slot: 2 scheduled_witness: 1.6.10 scheduled_time: 2019-02-27T16:47:54 now: 2019-02-27T16:47:54 
2874001ms th_a       witness.cpp:197               block_production_loo ] Got exception while generating block:
10 **assert_exception: Assert Exception
proposal != proposal_idx.end():** 

     db_sidechain.cpp:147 processing_sidechain_proposals
    {"witness_id":"1.6.10"}
    th_a  db_block.cpp:517 _generate_block

    th_a  db_block.cpp:376 generate_block
2874001ms th_a       witness.cpp:199               block_production_loo ] Discarding all pending transactions in an attempt to prevent the same error from occurring the next time we try to produce a block
2874001ms th_a       witness.cpp:233               block_production_loo ] exception prodcing bloc

**Comment by bobinson** [comment]
@pbattu123 : are you running Peerplays `witness_node` compiled with `Release` option or `Debug` option ?

**Comment by pbattu123** [comment]
> @pbattu123 : are you running Peerplays `witness_node` compiled with `Release` option or `Debug` option ?

Debug option to figure out any issues...

**Comment by pixelplex** [comment]
@pbattu123 could you please specify the version that has been tested for this? I.e. have you tried the latest version with this, or was there a particular latest commit to `feature-sidechain` that you tried this after/on?

**Comment by pbattu123** [comment]
> @pbattu123 could you please specify the version that has been tested for this? I.e. have you tried the latest version with this, or was there a particular latest commit to `feature-sidechain` that you tried this after/on?
> 
> Asking because we can't reproduce this issue on the current source code, and a very simiar problem has been fixed in [this commit](https://github.com/peerplays-network/peerplays/commit/329c75668f392e57e588061e18e98762fae82c63).
> 
> If this is being run based on the current source code - please let us know, and provide some more details.
> 
> Otherwise, please try to run this in sterile environemnt (clean Ubuntu 16.04, no datadir from the previous node(s)).

Yes, It was tested on Feb 25th commit, I have tried couple of times(one with clean environment)

**Comment by pixelplex** [comment]
@pbattu123 
Alright, I see. Much as we'd like to help, we haven't been able to reproduce it.
So if you could share more detailed steps it might help.

**Comment by pixelplex** [comment]
@pbattu123 also a proper log would be required. A good example on providing logs can be found [here](https://github.com/peerplays-network/peerplays/issues/20).

**Comment by pbattu123** [comment]
Today again I tried with fresh build after cleaning the environment and I am unable to reproduce the issue. 
Hence closing the issue
