### ISSUE TITLE
Fee deducting in core token(i.e. TEST) on withdrawing BTC from ppy node

### ISSUE THREAD

**Issue by pbattu123** [peerplays-network/peerplays#26]
Observe the balance on PPY account. Now withdraw BTC from PPY account and watch out for account balance, Fee deducted from TEST token balance.

**Comment by bobinson** [comment]
Peerplays node is running in TESTNET mode ?

**Comment by pbattu123** [comment]
> Peerplays node is running in TESTNET mode ?

Nope, This was tested in -regtest mode

**Comment by pixelplex** [comment]
@pbattu123 I would refer you to Fee Pool on Graphene. http://docs.bitshares.org/bitshares/user/assets-faq.html#fee-pool
This same process is applicable to PeerPlays.

pBTC is an asset on PeerPlays. As with any other asset, the fees can't be paid in pBTC if it doesn't have a fee pool.

There never was a requirement for pBTC tx fees to be paid in pBTC. If this is a requirement, Fee Pool needs to be created for the asset.

**Comment by pixelplex** [comment]
Not entirely sure what you refer to as `TEST token` here, though.

**Comment by pbattu123** [comment]
> Not entirely sure what you refer to as `TEST token` here, though.

The core token for the version of feature-sidechain is TEST. I believe you are working on the same version.

**Comment by pbattu123** [comment]
> @pbattu123 I would refer you to Fee Pool on Graphene. http://docs.bitshares.org/bitshares/user/assets-faq.html#fee-pool
> This same process is applicable to PeerPlays.
> 
> pBTC is an asset on PeerPlays. As with any other asset, the fees can't be paid in pBTC if it doesn't have a fee pool.
> 
> There never was a requirement for pBTC tx fees to be paid in pBTC. If this is a requirement, Fee Pool needs to be created for the asset.

Thank you for the clarification. I will close the issue once it gets clarified internally(Whether to create feel pool for dApps(like bets on BookiePro) with pBTC, apart from pBTC to BTC transactions)

**Comment by pixelplex** [comment]
@pbattu123 You are welcome. However, fee pool is standard Graphene functionality for UIAs (user-issued assets) in general. Therefore, if there's a fee pool for pBTC or any other asset, it affects the whole asset, and not just an asset within one or more dapps. I believe certain limitations on where to allow and where to forbid the usage of fee pools for assets can be set for this or that asset, but rather on the application layer, not on the protocol. Messing with this stuff on protocol level would be counterproductive IMO.

**Comment by bobinson** [comment]
With the Bitcoin Sidechain project is now implemented via SONs this is no more required.
