### ISSUE TITLE
make develop branch build in ubuntu 18.04

### ISSUE THREAD

**Issue by oxarbitrage** [peerplays-network/peerplays#4]
https://github.com/PBSA/peerplays/issues/24

related bitshares pull requests to port: 

https://github.com/bitshares/bitshares-fc/pull/7
https://github.com/bitshares/bitshares-core/pull/921

**Comment by xeroc** [comment]
Can you send a pull request, please?

**Comment by bobinson** [comment]
We have completed upgrade to Ubuntu 18.04 and its under QA

**Comment by bobinson** [comment]
fixed with:

https://github.com/peerplays-network/peerplays/pull/75


https://github.com/peerplays-network/peerplays/pull/114
