### ISSUE TITLE
possible log appending issue

### ISSUE THREAD

**Issue by bobinson** [peerplays-network/peerplays#40]
Verify the issue Log file of current hour gets overwritten by default as mentioned in 
https://github.com/bitshares/bitshares-core/issues/809 is applicable for Peerplays.

If so, fix the same. The base branch can be : https://github.com/peerplays-network/peerplays/tree/qa_gpos_18.04

**Acceptance Criteria**

- Tests should pass on Ubuntu 18.04, GCC-5.5, Boost Library 1.67.0
-  The fix should be merged to https://github.com/peerplays-network/peerplays/tree/qa_gpos_18.04

**Comment by bobinson** [comment]
@srpatel19590 - can you point me the to related PR ?

**Comment by srpatel19590** [comment]
@bobinson https://github.com/bitshares/bitshares-fc/pull/56/files

**Comment by bobinson** [comment]
@srpatel19590  - in the Peerplays repo & not in the bitshares repo

**Comment by srpatel19590** [comment]
@bobinson https://github.com/PBSA/peerplays-fc/pull/3

**Comment by bobinson** [comment]
@pbattu123  - we will need to fix this in GPOS and with ubuntu upgrade if possible

**Comment by bobinson** [comment]
addressed via https://github.com/peerplays-network/peerplays-fc/pull/6
