### ISSUE TITLE
ubuntu 18.04 build failing in branch qa_gpos_18.04

### ISSUE THREAD

**Issue by oxarbitrage** [peerplays-network/peerplays#44]
I tried to install with ubuntu 18.04 however it failed with error at:

https://github.com/peerplays-network/peerplays/tree/qa_gpos_18.04

**Comment by bobinson** [comment]
@oxarbitrage  - Thank you. can you share steps & the error message as well ?

**Comment by oxarbitrage** [comment]
my apologies, intention was to paste this link to the issue: https://github.com/oxarbitrage/logs/blob/master/peerplays_build_error.txt

**Comment by bobinson** [comment]
This is possibly due to gcc7

**Comment by bobinson** [comment]
this is fixed.
